### PR TITLE
Remove .npmignore and just publish lib files

### PR DESCRIPTION
**Pull request by sorrycc**
```bash
$ pkgfiles

PATH                                 SIZE      %
lib/__tests__/init.js                230 B     1%
lib/ownKeys.js                       453 B     3%
lib/index.js                         624 B     4%
lib/handleAction.js                  814 B     5%
lib/createAction.js                  862 B     5%
package.json                         972 B     6%
lib/handleActions.js                 986 B     6%
lib/__tests__/handleActions-test.js  1.97 kB   12%
lib/__tests__/handleAction-test.js   2.41 kB   15%
lib/__tests__/createAction-test.js   2.56 kB   16%
README.md                            4.5 kB    27%
```

### CODE REVIEW

**Comment by timche** [comment]
Thanks for this PR. This would still publish the `__tests__` in files `lib`, right? If yes, should we exclude them as well?

**Comment by alexgorbatchev** [comment]
Ideally tests should be excluded.

**Comment by timche** [comment]
@alexgorbatchev What is the reason why they should?

**Comment by alexgorbatchev** [comment]
@timche IMO, an NPM package is distribution, so it should only include distribution files required to run the files. The test files will never be used by the consumer, so why package them? :)

**Comment by timche** [comment]
Oh, sorry, my mistake. I've read `include` instead of `exclude`. Nvm :)

**Comment by timche** [comment]
@sorrycc Can you please adjust your PR and exclude the test files?

**Comment by sorrycc** [comment]
Done.

```bash
$ pkgfiles

PATH                  SIZE     %
lib/ownKeys.js        453 B    5%
lib/index.js          624 B    7%
lib/handleAction.js   814 B    9%
lib/createAction.js   862 B    9%
package.json          976 B    11%
lib/handleActions.js  986 B    11%
README.md             4.5 kB   49%

DIR                   SIZE     %
lib/                  3.74 kB  41%
.                     9.22 kB  100%

PKGFILES SUMMARY
Size on Disk with Dependencies  ~54.43 MB
Size with Dependencies          ~29.35 MB
Publishable Size                ~9.22 kB
Number of Directories           2
Number of Files                 7
```

**Comment by timche** [comment]
Merged, thanks!

**Pull request merged**
