### PR TITLE
Check type of payload creator

### PR DESCRIPTION
**Pull request by yangmillstheory**
This takes care of the first example in the `createAction` spec outlined [here](https://github.com/acdlite/redux-actions/pull/128#issuecomment-244896176).

This contains breaking changes, so it might be worth including in https://github.com/acdlite/redux-actions/issues/122.

### CODE REVIEW

**Comment by timche** [comment]
With the increase of checks and errors, I'd suggest to use [invariant](https://www.npmjs.com/package/invariant). It is already optimised for development and production with checking `process.env.NODE_ENV`.

**Comment by yangmillstheory** [comment]
Using `invariant` per your suggestion now.

Can you explain the behavior when `process.env.NODE_ENV === 'production`? I'm not familiar with this library and couldn't quite figure it out via the README.

From my point of view the main benefit is reducing the boilerplate of throwing errors on certain conditions.

**Comment by yangmillstheory** [comment]
For the `invariant` usage, I decided not to go with [this approach](https://github.com/ReactTraining/react-router/issues/545#issue-50437674), since the original error message is actually shorter than the "minified exception" message.

**Comment by yangmillstheory** [comment]
@timche is it possible to change the base branch to `v1.0.0`?

**Comment by timche** [comment]
Yes, I changed it.

**Comment by BerkeleyTrue** [comment]
Any way we can allow `null` for payload creator? 

I've always used `null` when I want to omit an argument instead of undefined. I'm still hesitant to use `undefined`.

**Comment by timche** [comment]
LGTM!

**Comment by yangmillstheory** [comment]
@timche with this merge, [`v.1.0.0`](https://github.com/acdlite/redux-actions/projects/1) is good to go.

**Pull request merged**
