### PR TITLE
support adding meta to error actions

### PR DESCRIPTION
**Pull request by jreinert**
this allows creating actions like this:

``` js
const actionCreator = createAction('TYPE', null, (_, meta) => meta);
actionCreator(new Error('foobar'), { foo: 'bar' });
// => { type: 'TYPE', payload: Error: 'foobar', meta: { foo: 'bar' }, error: true }
```

### CODE REVIEW

**Comment by jreinert** [comment]
please note that travis isn't failing because of any failing tests

**Comment by timche** [comment]
Can you please rebase? I will have a look at it again then, but looks good so far.

**Comment by jreinert** [comment]
It's a bit obsolete now since there was some refactoring to the action creator apparently. The test is maybe nice to have anyway. It's up to you, of course, but I won't cry tears of blood if you decide not to merge ;)

**Comment by timche** [comment]
Oh, yeah, forgot about that change. I'm fine with that test, I'll merge it, thanks :)

**Pull request merged**
