### PR TITLE
set error to true when payload instanceof Error

### PR DESCRIPTION
**Pull request by xiaohanzhang**
Should set error to true when payloadCreator return error

### CODE REVIEW

**Comment by yangmillstheory** [comment]
@xiaohanzhang Thanks for the contribution!

- can you write some tests around this?
- can you describe some specific use cases (when I have an error, I usually pass the error to the action creator directly)?

**Comment by yangmillstheory** [comment]
#43 is related.

@xiaohanzhang can you describe the use case?

@timche if the use case makes sense, I don't see a problem with merging this, as it seems to have been asked for and supported before.

**Comment by xiaohanzhang** [comment]
@yangmillstheory Thanks for great work and quick reply, I added a test for it
use case:
```
const fooAction = createAction('FOO', (...args) => {
  return isValid(args) ? {foo: 'bar'} : new Error('arguments is not valid');
});
```
I feel it will make more sense to put arguments validator inside actions, otherwise we need check it in every components.
With current implementation, I need create another wrapper for real action:
```
const fooActionWrapper = (...args) => {
  return isValid(args) ? fooAction(...args) : fooAction(new Error());
}
```

**Comment by yangmillstheory** [comment]
Thanks @xiaohanzhang. I think we should merge (pending @timche's feedback), but I would like to understand this a bit deeper, beyond avoiding writing wrappers. 

Can you give a couple of examples of an actual flow in your application where this comes in useful? What kind of validation are you doing in your payload creators?

**Comment by xiaohanzhang** [comment]
We have some rest api action,  I want add more client-side validation before it send to server. 
It been used by many components and projects. So I hope can put the validator inside action.

**Comment by yangmillstheory** [comment]
@timche please let us know if there are any blockers.

**Comment by holybom** [comment]
Hi, this new change doesn't seem to affect payloadCreator that returns a Promise, there's no error field in the dispatched action. I'm using redux-promise as well.

`export const myAction = createAction('ACTION_TYPE', () => myAsyncFunc()); `

myAsyncFunc does some network requests and returns a Promise that can resolve into an Error. Can you suggest a way to make it work?

**Comment by xiaohanzhang** [comment]
@holybom I usually just throw an error inside myAsyncFunc, redux-promise will catch that error:
https://github.com/acdlite/redux-promise/blob/master/src/index.js#L19

**Pull request merged**
