### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by dustyburwell**
Add a LICENSE file for better discoverability of the LICENSE.

### CODE REVIEW

**Comment by timche** [comment]
@acdlite What do you think of this? Should we add a license?

**Comment by timche** [comment]
@dustyburwell Can you please rebase, so Travis doesn't fail anymore?

**Comment by alexgorbatchev** [comment]
@dustyburwell ping

**Comment by dustyburwell** [comment]
Sure thing

**Comment by dustyburwell** [comment]
Done

**Comment by timche** [comment]
Thanks, merged :)

**Pull request merged**
