### PR TITLE
Async actions

### PR DESCRIPTION
**Pull request by johanneslumpe**
This allows us to handle async actions, see #2

### CODE REVIEW

**Comment by johanneslumpe** [comment]
@acdlite please review and check if i missed anything :)

**Comment by acdlite** [comment]
This looks good. Do you mind if we wait a bit before merging though? Still not totally sure this approach is best. It'd be nice to find a solution that works for observables, too (e.g. polling a server).

**Comment by johanneslumpe** [comment]
Sure, let's wait a bit and see if we come up with something better. Polling a server though would always dispatch an action with the 'end' status, right? It just wouldn't have `error` set, so it would use the `next` function.

**Comment by ralphschindler** [comment]
Has a best practice emerged for this yet? Thanks.

**Comment by marr** [comment]
Any updates on this?

**Comment by laurentdesmet** [comment]
Is this something that will be merged somewhere in the future? Async actions are fairly common so it would be nice if there is some kind of standard solution for this using the redux-actions library instead of implementing a custom async implementation using the `meta` field.

**Comment by timche** [comment]
We can't merge this PR, but we will definitely work on that asap. If we the author is willing to update this PR, we can make it happen here.

**Comment by alexFaunt** [comment]
@timche @acdlite  Any thoughts on this since it was last considered?

I've been thinking of:
```javascript
{
first() {
  // If payload is a promise this is fired
},
next() {
 // if payload is an object, but not an error this is fired
},
throw() {
 // if payload is an error object this is fired
}
}
```

This allows first class handling of pending actions without a breaking change. I've got a working version as a fork and happy to clean it up for a PR if you see fit. 

But if you were to use something more like a stream for polling (mentioned above), I'd suggest renaming the handlers to next, done and throw. Where 'next' processes any streamed values and 'done' being called with the final value. Promises would call 'next' once at the start, and then 'done' when complete. This would be a big breaking change though, and would need more thought and proper use cases setting out as i'm not sure theres a huge demand for such behaviour.

**Pull request closed without merging**
