### PR TITLE
Add support for default or initial state to handleAction

### PR DESCRIPTION
**Pull request by seniorquico**
Fix for #23.

### CODE REVIEW

**Comment by timche** [comment]
Hey @seniorquico, can you please rebase so the tests are running against the latest master? Thanks.

**Comment by seniorquico** [comment]
@timche Done. Let me know if I can help in any other way. Thanks!

**Comment by timche** [comment]
Thanks, I've merged it :)

**Comment by xml** [comment]
@timche, This is on master now, but doesn't seem to be in a release, in case you intended that. The docs for it are now showing on the homepage, but the code I can `npm install` (v. 0.9.1) doesn't include these changes (specifically, `defaultState`).

**Comment by yangmillstheory** [comment]
Right, I forked this repo so I can get the latest unreleased fixes in master. Not sure why it hasn't been released.

**Comment by timche** [comment]
Sorry guys, I'll reach out to @acdlite asap to release the latest master on npm.

**Comment by timche** [comment]
New version has been published on npm! :)

**Pull request merged**
